### ISSUE TITLE
第一次ハードコーディング駆逐作戦

### ISSUE THREAD

**Issue by Colk-tech** [brokenManager/Gorilla-TRPG-suporter#31]
ーーー現場からは異常です。

**Comment by Colk-tech** [comment]
以上だカス

**Comment by Colk-tech** [comment]
っていうか[WIP]でいいだろこれ

**Comment by isso0424** [comment]
草

**Comment by Colk-tech** [comment]
```fuck_hardcoding```で作業します

**Comment by Colk-tech** [comment]
42670cbc9fcccddf6d4c0db391c6e264b57998e5 を参照していただきたい
JSONファイル中に"{}"が含まれるものを参照しようとすると必ずエラーが起きます



(例)
```
from jsonmes import *
msg = JSONMessage()
print (msg.get_message("commands","joined"))
```
(結果)
```
"C:\Program Files (x86)\Python37-32\python.exe" U:/Repositories/brokenManager/Gorilla-TRPG-suporter/main.py
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "U:/Repositories/brokenManager/Gorilla-TRPG-suporter/main.py", line 55, in on_message
    print (msg.get_message("commands","joined"))
  File "U:\Repositories\brokenManager\Gorilla-TRPG-suporter\jsonmes.py", line 31, in get_message
    return msg.format(*kargs)
IndexError: tuple index out of range
```



どうして...
@loxygenK 助けてクレメンス

**Comment by isso0424** [comment]
なんだこれw

**Comment by Colk-tech** [comment]
***help wanted*** **(hakushinn)**

**Comment by isso0424** [comment]
こっちのやつやったらみてみるわ

**Comment by Colk-tech** [comment]
たすかる

**Comment by loxygenK** [comment]
```
これあの
内部でformatできるようになってて
つまりget_message(scope, name, hoge, fuga)ができる
という仕様にしてたから起こったんや
生きててごめんなさいをしている
```
という仕様変更をしたことを伝え忘れました
生きててごめんなさいをしている

**Comment by Colk-tech** [comment]
草
hoge fugaが{}に入るって認識でええ？

**Comment by loxygenK** [comment]
ｿｰﾅﾉ…すまんかった、ホントにすまんかった()

**Comment by Colk-tech** [comment]
盛大なるいきててごめんなさいで面白いのでヨシ！

**Comment by Colk-tech** [comment]
This should be closed because of #33
